version: '3'
services:
  qqbot:
    image: asupc/qqbot
    restart: always
    privileged: true
    container_name: qqbot1
    ports:
      - 5010:5010
    volumes:
      - ./config:/app/linux-x64/config
      - ./db:/app/linux-x64/db
      - ./logs:/app/linux-x64/logs
      - ./scripts:/app/linux-x64/scripts